test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %> # ensures tests files go to tmp/

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudinary:
  service: Cloudinary
  url: <%= ENV['CLOUDINARY_URL'] %>
